# Generated by Django 3.2.13 on 2022-05-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
